/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package itinerary;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author bapearson
 */
public class Itinerary extends javax.swing.JFrame {

    /**
     * Creates new form Itinerary
     */
    String[] airlineNameArray = {"Delta","Southwest","Virgin"};
    List<Account> accountList = new ArrayList<Account>();
    List<CreditCard> creditCardList = new ArrayList<CreditCard>();
    Route[] routeArray = {new Route(),new Route(),new Route(),new Route(),
                        new Route(),new Route(),new Route(),new Route(),
                        new Route(),new Route(),new Route(),new Route(),new Route(),new Route(),
                        new Route(),new Route(),new Route(),new Route(),
                        new Route(),new Route(),new Route(),new Route(),new Route(),new Route(),
                        new Route(),new Route(),new Route(),new Route(),
                        new Route(),new Route(),new Route(),new Route(),new Route(),new Route(),
                        new Route(),new Route(),new Route(),new Route(),
                        new Route(),new Route(),new Route(),new Route(),new Route(),new Route(),
                        new Route(),new Route(),new Route(),new Route(),
                        new Route(),new Route(),new Route(),new Route(),new Route(),new Route(),
                        new Route(),new Route(),new Route(),new Route(),
                        new Route(),new Route(),new Route(),new Route(),new Route(),new Route(),
                        new Route(),new Route(),new Route(),new Route(),
                        new Route(),new Route(),new Route(),new Route(),new Route(),new Route(),
                        new Route(),new Route(),new Route(),new Route(),
                        new Route(),new Route(),new Route(),new Route(),new Route(),new Route(),
                        new Route(),new Route(),new Route(),new Route(),
                        new Route(),new Route(),new Route(),new Route(),new Route(),new Route(),
                        new Route(),new Route(),new Route(),new Route(),
                        new Route(),new Route()};
    List<Route> routeList;
    public Itinerary() {
        initComponents();
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchDialog = new javax.swing.JDialog();
        toLabel = new javax.swing.JLabel();
        fromLabel = new javax.swing.JLabel();
        sortLabel2 = new javax.swing.JLabel();
        bookFlight = new javax.swing.JButton();
        toTextfield = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        DefaultListModel searchModel = new DefaultListModel();
        searchResults = new javax.swing.JList(searchModel);
        sortComboBox = new javax.swing.JComboBox();
        fromTextfield = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        bookDialog = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        bookCreditCards = new javax.swing.JList(new DefaultListModel());
        bookRouteDetails = new javax.swing.JLabel();
        bookPurchaseButton = new javax.swing.JButton();
        bookPrice = new javax.swing.JLabel();
        loginDialog = new javax.swing.JDialog();
        loginUsername = new javax.swing.JTextField();
        loginUsernameLabel = new javax.swing.JLabel();
        loginPasswordLabel = new javax.swing.JLabel();
        loginAirline = new javax.swing.JComboBox();
        loginAirlineLabel = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        loginList = new javax.swing.JList( );
        loginPassword = new javax.swing.JPasswordField();
        ccDialog = new javax.swing.JDialog();
        ccNumber = new javax.swing.JTextField();
        ccNumberLabel = new javax.swing.JLabel();
        ccExpirationLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ccCvc = new javax.swing.JTextField();
        ccAdd = new javax.swing.JButton();
        ccName = new javax.swing.JTextField();
        ccNameLabel = new javax.swing.JLabel();
        ccAirline = new javax.swing.JTextField();
        ccAirlineLabel = new javax.swing.JLabel();
        ccEdit = new javax.swing.JButton();
        ccRemove = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ccList = new javax.swing.JList();
        ccExpiration = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        accountsButton = new javax.swing.JButton();
        creditcardsButton = new javax.swing.JButton();
        searchButton = new javax.swing.JButton();

        toLabel.setText("To");

        fromLabel.setText("From");

        sortLabel2.setText("Sort by");

        bookFlight.setText("Book Flight");
        bookFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookFlightActionPerformed(evt);
            }
        });

        jScrollPane6.setViewportView(searchResults);

        sortComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Price", "Airline" }));
        sortComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortComboBoxActionPerformed(evt);
            }
        });

        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchDialogLayout = new javax.swing.GroupLayout(searchDialog.getContentPane());
        searchDialog.getContentPane().setLayout(searchDialogLayout);
        searchDialogLayout.setHorizontalGroup(
            searchDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchDialogLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(searchDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                    .addGroup(searchDialogLayout.createSequentialGroup()
                        .addGroup(searchDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchDialogLayout.createSequentialGroup()
                                .addComponent(toLabel)
                                .addGap(18, 18, 18))
                            .addGroup(searchDialogLayout.createSequentialGroup()
                                .addComponent(fromLabel)
                                .addGap(6, 6, 6)))
                        .addGroup(searchDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(fromTextfield)
                            .addComponent(toTextfield, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)))
                    .addGroup(searchDialogLayout.createSequentialGroup()
                        .addComponent(sortLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sortComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(searchDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bookFlight)
                    .addComponent(search))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        searchDialogLayout.setVerticalGroup(
            searchDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fromLabel)
                    .addComponent(fromTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(searchDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toLabel)
                    .addComponent(toTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(searchDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sortLabel2)
                    .addComponent(sortComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(searchDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bookFlight))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane3.setViewportView(bookCreditCards);

        bookPurchaseButton.setText("Purchase");
        bookPurchaseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookPurchaseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bookDialogLayout = new javax.swing.GroupLayout(bookDialog.getContentPane());
        bookDialog.getContentPane().setLayout(bookDialogLayout);
        bookDialogLayout.setHorizontalGroup(
            bookDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bookDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(bookRouteDetails, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bookDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bookPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bookPurchaseButton, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );
        bookDialogLayout.setVerticalGroup(
            bookDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bookDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bookDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(bookDialogLayout.createSequentialGroup()
                        .addComponent(bookPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bookPurchaseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bookDialogLayout.createSequentialGroup()
                        .addComponent(bookRouteDetails, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        loginUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginUsernameActionPerformed(evt);
            }
        });

        loginUsernameLabel.setText("Username");

        loginPasswordLabel.setText("Password");

        loginAirline.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Delta", "Southwest", "Virgin" }));

        loginAirlineLabel.setText("Airline");

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        loginList.setModel(new DefaultListModel());
        loginList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                loginListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(loginList);

        loginPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginPasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginDialogLayout = new javax.swing.GroupLayout(loginDialog.getContentPane());
        loginDialog.getContentPane().setLayout(loginDialogLayout);
        loginDialogLayout.setHorizontalGroup(
            loginDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginDialogLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(loginDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginDialogLayout.createSequentialGroup()
                        .addGroup(loginDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(loginPasswordLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(loginUsernameLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(loginAirlineLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(loginDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(addButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(loginAirline, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginDialogLayout.createSequentialGroup()
                                .addGroup(loginDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(loginPassword)
                                    .addComponent(loginUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                                .addGap(3, 3, 3))))
                    .addComponent(deleteButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        loginDialogLayout.setVerticalGroup(
            loginDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(loginDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, loginDialogLayout.createSequentialGroup()
                        .addGroup(loginDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(loginUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(loginUsernameLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(loginDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(loginPasswordLabel)
                            .addComponent(loginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(loginDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(loginAirline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(loginAirlineLabel))
                        .addGap(18, 18, 18)
                        .addComponent(addButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deleteButton)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        ccNumber.setToolTipText("All digits on the front of the card. Disregard spaces.");
        ccNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ccNumberActionPerformed(evt);
            }
        });

        ccNumberLabel.setText("Account Number");

        ccExpirationLabel.setText("Expiration");

        jLabel2.setText("CVC");

        ccCvc.setToolTipText("On the back of your card next to the signature line.");
        ccCvc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ccCvcActionPerformed(evt);
            }
        });

        ccAdd.setText("Add");
        ccAdd.setToolTipText("Add credit card to your wallet.");
        ccAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ccAddActionPerformed(evt);
            }
        });

        ccName.setToolTipText("All digits on the front of the card. Disregard spaces.");
        ccName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ccNameActionPerformed(evt);
            }
        });

        ccNameLabel.setText("Name");

        ccAirline.setToolTipText("All digits on the front of the card. Disregard spaces.");
        ccAirline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ccAirlineActionPerformed(evt);
            }
        });

        ccAirlineLabel.setText("Associated Airline");

        ccEdit.setText("Edit");
        ccEdit.setToolTipText("Add credit card to your wallet.");
        ccEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ccEditActionPerformed(evt);
            }
        });

        ccRemove.setText("Remove");
        ccRemove.setToolTipText("Add credit card to your wallet.");
        ccRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ccRemoveActionPerformed(evt);
            }
        });

        ccList.setModel(new DefaultListModel());
        ccList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ccList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                ccListValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(ccList);

        jLabel1.setText("MM/DD/YYYY");

        javax.swing.GroupLayout ccDialogLayout = new javax.swing.GroupLayout(ccDialog.getContentPane());
        ccDialog.getContentPane().setLayout(ccDialogLayout);
        ccDialogLayout.setHorizontalGroup(
            ccDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ccDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(ccDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ccDialogLayout.createSequentialGroup()
                        .addComponent(ccAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ccEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ccRemove))
                    .addGroup(ccDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(ccDialogLayout.createSequentialGroup()
                            .addComponent(ccAirlineLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(ccAirline, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(ccDialogLayout.createSequentialGroup()
                            .addGroup(ccDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ccNumberLabel)
                                .addComponent(ccExpirationLabel)
                                .addComponent(ccNameLabel))
                            .addGap(18, 18, 18)
                            .addGroup(ccDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addGroup(ccDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(ccDialogLayout.createSequentialGroup()
                                        .addComponent(ccExpiration, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ccCvc, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(ccNumber, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ccName))))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        ccDialogLayout.setVerticalGroup(
            ccDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ccDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ccDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ccDialogLayout.createSequentialGroup()
                        .addGroup(ccDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ccName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ccNameLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ccDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ccNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ccNumberLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ccDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ccExpirationLabel)
                            .addComponent(jLabel2)
                            .addComponent(ccCvc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ccExpiration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ccDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ccAirline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ccAirlineLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ccDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ccAdd)
                            .addComponent(ccEdit)
                            .addComponent(ccRemove))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        accountsButton.setText("Accounts");
        accountsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountsButtonActionPerformed(evt);
            }
        });

        creditcardsButton.setText("Credit Cards");
        creditcardsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditcardsButtonActionPerformed(evt);
            }
        });

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(creditcardsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(searchButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(accountsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(accountsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(creditcardsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void accountsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountsButtonActionPerformed
        // TODO add your handling code here:
        loginDialog.setVisible(true);
        loginDialog.setBounds(300,300,500,300);
    }//GEN-LAST:event_accountsButtonActionPerformed

    private void creditcardsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditcardsButtonActionPerformed
        // TODO add your handling code here:
        ccDialog.setVisible(true);
        ccDialog.setBounds(300,300,700,300);
    }//GEN-LAST:event_creditcardsButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        searchDialog.setVisible(true);
        searchDialog.setBounds(300,300,400,375);
    }//GEN-LAST:event_searchButtonActionPerformed

    private void bookFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookFlightActionPerformed
        // TODO add your handling code here:
        bookDialog.setVisible(true);
        bookDialog.setBounds(300, 300, 400, 300);

        int i = searchResults.getSelectedIndex();
        if (i >= 0) {
            bookRouteDetails.setText(routeList.get(i).getStart() + 
                    " to " + routeList.get(i).getFinish() + 
                    " for " + routeList.get(i).getDuration() + " hours");
            bookPrice.setText("$" + routeList.get(i).getPrice());

            accountList.add(new Account(loginUsername.getText(), loginPassword.getText(), loginAirline.getSelectedItem().toString()));
            ((DefaultListModel) bookCreditCards.getModel()).clear();
            for (CreditCard c : creditCardList) {
                if(c.getAirlineName().equals(routeList.get(i).getAirline()) || 
                        c.getAirlineName().equals("")) 
                {
                    String lastFour = c.getCcNumber().substring(c.getCcNumber().length() - 4);
                    ((DefaultListModel) bookCreditCards.getModel()).addElement(lastFour);
                }
            }
        }
    }//GEN-LAST:event_bookFlightActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        routeList = new ArrayList<Route>();
        String from = fromTextfield.getText();
        String to = toTextfield.getText();
        
        DefaultListModel searchResultsListModel = new DefaultListModel();
        searchResultsListModel = (DefaultListModel)searchResults.getModel();
        searchResultsListModel.removeAllElements();
        
        for(int i = 0; i < routeArray.length; i++)
        {
            if(from.equals(routeArray[i].getStart())
                    && to.equals(routeArray[i].getFinish()))
                routeList.add(routeArray[i]);
        }
        
        if(sortComboBox.getSelectedItem().equals("Price"))
        {
            Route.sort = 0;
            Collections.sort(routeList);       
        }
        else
        {
            Route.sort = 1;
            Collections.sort(routeList);
        }
        
        for(Route r : routeList)
        {
            searchResultsListModel.addElement(r.getAirline() +"  $"+ r.getPrice() +"  "+ r.getDuration() + " hrs");
        }
    }//GEN-LAST:event_searchActionPerformed

private void sortComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortComboBoxActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_sortComboBoxActionPerformed

private void loginUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginUsernameActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_loginUsernameActionPerformed

private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        accountList.add(new Account(loginUsername.getText(), loginPassword.getText(), loginAirline.getSelectedItem().toString()));
        ((DefaultListModel)loginList.getModel()).clear();
        for(Account a : accountList)
        {
            ((DefaultListModel)loginList.getModel()).addElement(a.getUsername() + " " + a.getAirlineName());
        }

}//GEN-LAST:event_addButtonActionPerformed

private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
    // TODO add your handling code here:
    //elements need to be removed in reverse order
    //to preserve indices
    int i = loginList.getSelectedIndex();
    if (i >= 0) {
        ((DefaultListModel)loginList.getModel()).clear();
        accountList.remove(i);
        for(Account a : accountList){
            ((DefaultListModel)loginList.getModel()).addElement(a.getUsername() + " " + a.getAirlineName());
        }
    }
}//GEN-LAST:event_deleteButtonActionPerformed

private void loginListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_loginListValueChanged
        // TODO add your handling code here:
    if(loginList.getSelectedValue() != null){
        int j = loginList.getSelectedIndex();
        loginUsername.setText(accountList.get(j).getUsername());
        loginPassword.setText(accountList.get(j).getPassword());
        loginAirline.setSelectedItem(accountList.get(j).getAirlineName());
    }
}//GEN-LAST:event_loginListValueChanged

private void loginPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginPasswordActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_loginPasswordActionPerformed

private void ccNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ccNumberActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_ccNumberActionPerformed

private void ccCvcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ccCvcActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_ccCvcActionPerformed

private void ccAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ccAddActionPerformed
       // TODO add your handling code here:
        String lastFour = ccNumber.getText().substring(ccNumber.getText().length() - 4);
        ((DefaultListModel) ccList.getModel()).addElement(lastFour + " " + ccAirline.getText());
        
        creditCardList.add(new CreditCard(ccName.getText(), ccNumber.getText(), ccExpiration.getText(), ccCvc.getText(), ccAirline.getText()));
        
}//GEN-LAST:event_ccAddActionPerformed

private void ccNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ccNameActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_ccNameActionPerformed

private void ccAirlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ccAirlineActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_ccAirlineActionPerformed

private void ccEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ccEditActionPerformed
        // TODO add your handling code here:
        
        for(CreditCard c : creditCardList){
            if(ccNumber.getText().equals(c.getCcNumber()))
                c.setAirlineName(ccAirline.getText());
        }
        
        ((DefaultListModel)ccList.getModel()).clear();
        for(CreditCard c : creditCardList){
            String lastFour = c.getCcNumber().substring(c.getCcNumber().length() - 4);
            ((DefaultListModel) ccList.getModel()).addElement(lastFour + " " + c.getAirlineName());
        }
            
}//GEN-LAST:event_ccEditActionPerformed

private void ccRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ccRemoveActionPerformed
        // TODO add your handling code here:
       DefaultListModel model;
        model = (DefaultListModel) ccList.getModel(); 
         //elements need to be removed in reverse order
            //to preserve indices
        int i = ccList.getSelectedIndex();
        if(i >= 0)
            creditCardList.remove(i);
        ((DefaultListModel)ccList.getModel()).clear();
        for(CreditCard c : creditCardList){
            String lastFour = c.getCcNumber().substring(c.getCcNumber().length() - 4);
            ((DefaultListModel) ccList.getModel()).addElement(lastFour + " " + c.getAirlineName());
        }
}//GEN-LAST:event_ccRemoveActionPerformed

private void ccListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_ccListValueChanged
// TODO add your handling code here:
    if(ccList.getSelectedValue() != null)
    {
        int i = ccList.getSelectedIndex();
        ccName.setText(creditCardList.get(i).getName());
        ccNumber.setText(creditCardList.get(i).getCcNumber());
        ccCvc.setText(creditCardList.get(i).getCvc());
        ccExpiration.setText(creditCardList.get(i).getExpiration());
        ccAirline.setText(creditCardList.get(i).getAirlineName());
    }
}//GEN-LAST:event_ccListValueChanged

private void bookPurchaseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookPurchaseButtonActionPerformed
// TODO add your handling code here:
    int i = searchResults.getSelectedIndex();
    JOptionPane.showMessageDialog(null, "You purchased a flight from " + 
            routeList.get(i).getStart() + " to " + routeList.get(i).getFinish() + ".\n" +
            "The flight will last " + routeList.get(i).getDuration() + " hours.\n"
                    + "Cost: $" + routeList.get(i).getPrice());
}//GEN-LAST:event_bookPurchaseButtonActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Itinerary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Itinerary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Itinerary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Itinerary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Itinerary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accountsButton;
    private javax.swing.JButton addButton;
    private javax.swing.JList bookCreditCards;
    private javax.swing.JDialog bookDialog;
    private javax.swing.JButton bookFlight;
    private javax.swing.JLabel bookPrice;
    private javax.swing.JButton bookPurchaseButton;
    private javax.swing.JLabel bookRouteDetails;
    private javax.swing.JButton ccAdd;
    private javax.swing.JTextField ccAirline;
    private javax.swing.JLabel ccAirlineLabel;
    private javax.swing.JTextField ccCvc;
    private javax.swing.JDialog ccDialog;
    private javax.swing.JButton ccEdit;
    private javax.swing.JTextField ccExpiration;
    private javax.swing.JLabel ccExpirationLabel;
    private javax.swing.JList ccList;
    private javax.swing.JTextField ccName;
    private javax.swing.JLabel ccNameLabel;
    private javax.swing.JTextField ccNumber;
    private javax.swing.JLabel ccNumberLabel;
    private javax.swing.JButton ccRemove;
    private javax.swing.JButton creditcardsButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel fromLabel;
    private javax.swing.JTextField fromTextfield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JComboBox loginAirline;
    private javax.swing.JLabel loginAirlineLabel;
    private javax.swing.JDialog loginDialog;
    private javax.swing.JList loginList;
    private javax.swing.JPasswordField loginPassword;
    private javax.swing.JLabel loginPasswordLabel;
    private javax.swing.JTextField loginUsername;
    private javax.swing.JLabel loginUsernameLabel;
    private javax.swing.JButton search;
    private javax.swing.JButton searchButton;
    private javax.swing.JDialog searchDialog;
    private javax.swing.JList searchResults;
    private javax.swing.JComboBox sortComboBox;
    private javax.swing.JLabel sortLabel2;
    private javax.swing.JLabel toLabel;
    private javax.swing.JTextField toTextfield;
    // End of variables declaration//GEN-END:variables
}
